import React from 'react';
import { useParams, Link } from 'react-router-dom';
import { useLanguage } from '../components/LanguageContext';
import { motion } from 'motion/react';
import { ArrowLeft, Calendar, Tag, Activity, Users, Target, Globe } from 'lucide-react';

const ProjectDetail: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const { content, language, langPath } = useLanguage();
  const t = content.projects.details;

  // Mock project data - normally fetched from an API/CMS based on the ID
  const project = {
    id: 'p1',
    title: language === 'fr' ? 'Plateforme EduDigital Bénin' : 'EduDigital Benin Platform',
    theme: 'Numérique',
    status: 'ongoing',
    date: '2024 - 2026',
    image: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=2070&auto=format&fit=crop',
    // HTML content generated by Quill.js
    description: language === 'fr' ? `
      <p>La plateforme <strong>EduDigital Bénin</strong> est une initiative phare visant à réduire la fracture numérique en milieu scolaire rural. Le projet se concentre sur trois axes majeurs :</p>
      <ul>
        <li>Installation de serveurs locaux de contenus pédagogiques (hors ligne).</li>
        <li>Formation technique des référents numériques locaux.</li>
        <li>Dotation de bibliothèques numériques mobiles de 50 tablettes par site.</li>
      </ul>
      <p>Ce projet s'inscrit dans la vision d'un système éducatif béninois <em>capable de résister aux crises</em> et d'offrir des ressources de qualité partout sur le territoire.</p>
    ` : `
      <p>The <strong>EduDigital Benin</strong> platform is a flagship initiative aimed at reducing the digital divide in rural school environments. The project focuses on three major axes:</p>
      <ul>
        <li>Installation of local educational content servers (offline).</li>
        <li>Technical training of local digital referents.</li>
        <li>Provision of mobile digital libraries of 50 tablets per site.</li>
      </ul>
      <p>This project is part of the vision of a Beninese educational system <em>capable of withstanding crises</em> and offering quality resources everywhere in the territory.</p>
    `,
    objectives: language === 'fr' ? `
      <ul>
        <li>Équiper 50 écoles rurales en solution numérique autonome.</li>
        <li>Former 100 enseignants aux pratiques du numérique éducatif.</li>
        <li>Impacter directement 15 000 élèves du secondaire.</li>
      </ul>
    ` : `
      <ul>
        <li>Equip 50 rural schools with autonomous digital solutions.</li>
        <li>Train 100 teachers in educational digital practices.</li>
        <li>Directly impact 15,000 secondary school students.</li>
      </ul>
    `,
    impact: language === 'fr' ? "Réduction de 40% de l'écart de performance entre les zones urbaines et rurales sur les matières scientifiques testées." : "40% reduction in the performance gap between urban and rural areas on tested science subjects.",
    location: "Godomey, Toffo, Allada",
    budget: "150,000,000 FCFA"
  };

  return (
    <div className="bg-white min-h-screen">
      {/* Back Navigation */}
      <div className="bg-white border-b border-gray-100 py-4 sticky top-20 z-40 backdrop-blur-md">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
           <Link to={langPath('/projects')} className="inline-flex items-center gap-2 text-sm font-black text-blue-950 uppercase tracking-widest hover:text-emerald-600 transition-colors group">
              <ArrowLeft size={18} className="group-hover:-translate-x-1 transition-transform" />
              {t.backToProjects}
           </Link>
        </div>
      </div>

      {/* Hero Header */}
      <section className="relative h-[60vh] lg:h-[70vh] flex items-end">
         <img 
           src={project.image} 
           alt={project.title}
           className="absolute inset-0 w-full h-full object-cover"
           referrerPolicy="no-referrer"
         />
         <div className="absolute inset-0 bg-gradient-to-t from-blue-950 via-blue-950/40 to-transparent" />
         
         <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10 w-full pb-20">
            <motion.div 
               initial={{ opacity: 0, y: 20 }}
               animate={{ opacity: 1, y: 0 }}
               className="space-y-6"
            >
               <div className="flex flex-wrap gap-3">
                  <span className="px-4 py-2 bg-emerald-500 text-white text-[10px] font-black uppercase tracking-widest rounded-full">{project.theme}</span>
                  <span className="px-4 py-2 bg-white/10 text-white text-[10px] font-black uppercase tracking-widest rounded-full border border-white/20 backdrop-blur-md">
                    {project.status === 'ongoing' ? content.projects.filters.ongoing : content.projects.filters.completed}
                  </span>
               </div>
               <h1 className="text-2xl sm:text-3xl md:text-5xl lg:text-7xl font-black text-white leading-tight uppercase tracking-tighter">
                  {project.title}
               </h1>
            </motion.div>
         </div>
      </section>

      {/* Main Content */}
      <section className="py-20 lg:py-32">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-20">
            {/* Left Column: Description */}
            <div className="lg:col-span-2 space-y-20">
               {/* Metadata Bar */}
               <div className="grid grid-cols-2 md:grid-cols-4 gap-8 pb-12 border-b border-gray-100">
                  <div className="space-y-1">
                     <span className="text-[10px] font-black text-gray-400 uppercase tracking-widest block">{t.date}</span>
                     <div className="flex items-center gap-2 text-blue-950 font-bold">
                        <Calendar size={16} className="text-emerald-500" />
                        {project.date}
                     </div>
                  </div>
                  <div className="space-y-1">
                     <span className="text-[10px] font-black text-gray-400 uppercase tracking-widest block">{t.status}</span>
                     <div className="flex items-center gap-2 text-blue-950 font-bold">
                        <Activity size={16} className="text-blue-500" />
                        {project.status === 'ongoing' ? content.projects.filters.ongoing : content.projects.filters.completed}
                     </div>
                  </div>
                  <div className="space-y-1">
                     <span className="text-[10px] font-black text-gray-400 uppercase tracking-widest block">{t.location}</span>
                     <div className="flex items-center gap-2 text-blue-950 font-bold">
                        <Globe size={16} className="text-amber-500" />
                        {project.location}
                     </div>
                  </div>
                  <div className="space-y-1">
                     <span className="text-[10px] font-black text-gray-400 uppercase tracking-widest block">{t.budget}</span>
                     <div className="flex items-center gap-2 text-blue-950 font-bold">
                        <Tag size={16} className="text-purple-500" />
                        {project.budget}
                     </div>
                  </div>
               </div>

               {/* Description Sections */}
               <div className="space-y-16">
                  <motion.div 
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    className="space-y-8"
                  >
                     <div className="flex items-center gap-4">
                        <div className="w-1.5 h-8 bg-emerald-500 rounded-full" />
                        <h2 className="text-xl lg:text-2xl font-black text-blue-950 uppercase tracking-tight">{t.description}</h2>
                     </div>
                     {/* QUILL.JS COMPATIBLE CONTAINER */}
                     <div 
                       className="markdown-body text-lg text-gray-600 leading-relaxed quill-content prose prose-blue lg:prose-xl max-w-none"
                       dangerouslySetInnerHTML={{ __html: project.description }}
                     />
                  </motion.div>

                  <motion.div 
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    className="space-y-8 bg-blue-50/50 p-10 lg:p-14 rounded-[3.5rem] border border-blue-100/50"
                  >
                     <div className="flex items-center gap-4">
                        <div className="w-1.5 h-8 bg-blue-600 rounded-full" />
                        <h3 className="text-3xl font-black text-blue-950 uppercase tracking-tight">{t.objectives}</h3>
                     </div>
                     <div 
                       className="markdown-body text-lg text-gray-600 leading-relaxed quill-content prose prose-blue max-w-none"
                       dangerouslySetInnerHTML={{ __html: project.objectives }}
                     />
                  </motion.div>
               </div>
            </div>

            {/* Right Column: Statistics / CTA */}
            <div className="space-y-8 lg:sticky lg:top-40 h-fit">
               <div className="bg-emerald-950 rounded-[3rem] p-10 text-white space-y-10 shadow-2xl shadow-emerald-950/20">
                  <div className="space-y-2">
                     <Target className="text-emerald-400 mb-4" size={40} />
                     <h4 className="text-xl font-black uppercase tracking-tight">{t.impact}</h4>
                  </div>
                  <p className="text-emerald-100 text-lg font-medium leading-relaxed italic">
                     "{project.impact}"
                  </p>
                  
                  <div className="space-y-6 pt-10 border-t border-white/10 text-center">
                     <div className="flex items-center justify-between">
                        <Users size={20} className="text-emerald-400" />
                        <span className="text-4xl font-black">15,000+</span>
                     </div>
                     <p className="text-[10px] font-black uppercase tracking-wider text-emerald-300">{t.beneficiaries}</p>
                  </div>
               </div>

               <div className="bg-gray-50 rounded-[3rem] p-10 border border-gray-100 space-y-6">
                  <h4 className="font-black text-blue-950 uppercase tracking-widest text-sm">{t.supportTitle}</h4>
                  <p className="text-gray-600 font-medium text-sm leading-relaxed">
                     {t.supportText}
                  </p>
                  <Link 
                    to={langPath('/donate')}
                    className="w-full py-5 bg-blue-600 text-white rounded-2xl font-black uppercase tracking-widest text-xs flex items-center justify-center gap-2 hover:bg-emerald-600 transition-all shadow-xl shadow-blue-600/20"
                  >
                     {t.donateCTA}
                  </Link>
               </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};

export default ProjectDetail;
